import { TeacherData } from './types';

export const CLASSES = ['VII A', 'VII B', 'VII C', 'VIII A', 'VIII B', 'VIII C', 'IX A', 'IX B', 'IX C'];

export interface ScheduleRow {
  jam: string;
  waktu: string;
  activity?: string;
  isBreak?: boolean;
}

export interface DaySchedule {
  day: string;
  rows: ScheduleRow[];
  allocatableSlots: string[];
}

export const COLOR_PALETTE = [
  'bg-red-100 text-red-800 border-red-200',
  'bg-orange-100 text-orange-800 border-orange-200',
  'bg-amber-100 text-amber-800 border-amber-200',
  'bg-yellow-100 text-yellow-800 border-yellow-200',
  'bg-lime-100 text-lime-800 border-lime-200',
  'bg-green-100 text-green-800 border-green-200',
  'bg-emerald-100 text-emerald-800 border-emerald-200',
  'bg-teal-100 text-teal-800 border-teal-200',
  'bg-cyan-100 text-cyan-800 border-cyan-200',
  'bg-sky-100 text-sky-800 border-sky-200',
  'bg-blue-100 text-blue-800 border-blue-200',
  'bg-indigo-100 text-indigo-800 border-indigo-200',
  'bg-violet-100 text-violet-800 border-violet-200',
  'bg-purple-100 text-purple-800 border-purple-200',
  'bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200',
  'bg-pink-100 text-pink-800 border-pink-200',
  'bg-rose-100 text-rose-800 border-rose-200',
  'bg-stone-100 text-stone-800 border-stone-200',
  'bg-blue-50 text-blue-900 border-blue-200',
  'bg-red-50 text-red-900 border-red-200',
];

export const SCHEDULE_DATA: DaySchedule[] = [
  {
    day: "SENIN",
    allocatableSlots: ["2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 06.45", activity: "Persiapan Upacara Bendera", isBreak: true },
      { jam: "1", waktu: "06.45 - 07.40", activity: "Upacara Bendera", isBreak: true },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "SELASA",
    allocatableSlots: ["1", "2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Ar-Rahman", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "RABU",
    allocatableSlots: ["1", "2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Al Waqi'ah", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "KAMIS",
    allocatableSlots: ["1", "2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Isitighotsah", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "JUM'AT",
    allocatableSlots: ["1", "2", "3", "4", "5"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Yasin", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
    ]
  },
  {
    day: "SABTU",
    allocatableSlots: ["2", "3", "4", "5", "6"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Asma'ul Husna dan Juz 'Amma", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40", activity: "Sabtu Sehat Jiwa Raga", isBreak: true },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 12.00", activity: "Sholat Dhuhur Berjamaah", isBreak: true },
      { jam: "", waktu: "", activity: "Kegiatan Pengembangan Diri (Ekstra Kurikuler)", isBreak: true },
    ]
  }
];

export const TEACHER_DATA: TeacherData[] = [
  {
    id: 1,
    no: "1",
    name: "Dra. Sri Hayati",
    nip: "196702041992022006",
    rank: "Penata Tk. I",
    gol: "III d",
    subject: "Bahasa Indonesia",
    code: "BIN-SH",
    hoursVII: {},
    hoursVIII: { B: 6, C: 6 },
    hoursIX: { A: 6, B: 6, C: 6 },
    additionalTask: "Wali Kelas IX B, Guru Wali",
    additionalHours: 4,
    totalHours: 34
  },
  {
    id: 2,
    no: "2",
    name: "Bakhtiar Rifai, SE",
    nip: "196610011993031009",
    rank: "Penata Tk. I",
    gol: "III d",
    subject: "Ilmu Pengetahuan Sosial",
    code: "IPS-BR",
    hoursVII: {},
    hoursVIII: { A: 4, B: 4, C: 4 },
    hoursIX: {},
    additionalTask: "Kepala Laboratorium, Guru Wali",
    additionalHours: 14,
    totalHours: 26
  },
  {
    id: 3,
    no: "3",
    name: "Moch. Husain Rifai Hamzah, S.Pd.",
    nip: "197504112008011011",
    rank: "Penata Muda Tk I",
    gol: "III b",
    subject: "Penjas Orkes",
    code: "PJOK-MH",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: { A: 3, B: 3, C: 3 },
    hoursIX: { A: 3, B: 3, C: 3 },
    additionalTask: "Guru Wali, Wali Kelas IX A",
    additionalHours: 4,
    totalHours: 31
  },
  {
    id: 4,
    no: "4",
    name: "Rudi Hermawan, S.Pd.I",
    nip: "197305152008011003",
    rank: "Penata Muda",
    gol: "III a",
    subject: "Pendidikan Agama Islam",
    code: "PAI-RH",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: { A: 3, B: 3, C: 3 },
    hoursIX: { A: 3, B: 3, C: 3 },
    additionalTask: "Guru Wali",
    additionalHours: 2,
    totalHours: 29
  },
  {
    id: 5,
    no: "5",
    name: "Okha Devi Anggraini, S.Pd.",
    nip: "199610232024212008",
    rank: "Penata Muda",
    gol: "III a",
    subject: "Bimbingan Konseling",
    code: "BK-OD",
    hoursVII: { A: 1, B: 1, C: 1 },
    hoursVIII: {},
    hoursIX: { A: 1, B: 1, C: 1 },
    additionalTask: "Wali Kelas VII C, Guru Wali",
    additionalHours: 4,
    totalHours: 10
  },
  {
    id: 6,
    no: "6",
    name: "Eka Hariyati, S. Pd.",
    nip: "199212172024212003",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "PPKn",
    code: "PKN-EH",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: { A: 3, B: 3, C: 3 },
    hoursIX: { A: 3, B: 3, C: 3 },
    additionalTask: "Wali Kelas VIII B, Guru Wali",
    additionalHours: 4,
    totalHours: 31
  },
  {
    id: 7,
    no: "7",
    name: "Mikoe Wahyudi Putra, ST., S. Pd.",
    nip: "198506012024211004",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Bimbingan Konseling",
    code: "BK-MW",
    hoursVII: {},
    hoursVIII: { A: 1, B: 1, C: 1 },
    hoursIX: {},
    additionalTask: "Wakasek, Guru Wali",
    additionalHours: 14,
    totalHours: 17
  },
  {
    id: 8,
    no: "8",
    name: "Purnadi, S. Pd.",
    nip: "199606192024211001",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Matematika",
    code: "MAT-PU",
    hoursVII: {},
    hoursVIII: { B: 5, C: 5 },
    hoursIX: { A: 5, B: 5, C: 5 },
    additionalTask: "Wali Kelas IX C, Guru Wali",
    additionalHours: 4,
    totalHours: 29
  },
  {
    id: 9,
    no: "9",
    name: "Israfin Maria Ulfa, S.Pd",
    nip: "199612212024212004",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Ilmu Pengetahuan Sosial",
    code: "IPS-MU",
    hoursVII: { A: 4, B: 4, C: 4 },
    hoursVIII: {},
    hoursIX: { A: 4, B: 4, C: 4 },
    additionalTask: "Wali Kelas VII A, Guru Wali",
    additionalHours: 4,
    totalHours: 28
  },
  {
    id: 10,
    no: "10",
    name: "Syadam Budi Satrianto, S.Pd",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Bahasa Jawa",
    code: "BAJA-SB",
    hoursVII: { A: 2, B: 2, C: 2 },
    hoursVIII: { A: 2, B: 2, C: 2 },
    hoursIX: { A: 2, B: 2, C: 2 },
    additionalTask: "Wali Kelas VIII A, Guru Wali",
    additionalHours: 4,
    totalHours: 22
  },
  {
    id: 11,
    no: "11",
    name: "Rebby Dwi Prataopu, S.Si",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Ilmu Pengetahuan Alam",
    code: "IPA-RB",
    hoursVII: { A: 5, B: 5 }, // Inferred from "5 5"
    hoursVIII: {},
    hoursIX: { A: 5, B: 5, C: 5 },
    additionalTask: "Wali Kelas VII B, Guru Wali",
    additionalHours: 4,
    totalHours: 29
  },
  {
    id: 12,
    no: "12",
    name: "Mukhamad Yunus, S.Pd",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Ilmu Pengetahuan Alam",
    code: "IPA-MY",
    hoursVII: {},
    hoursVIII: { A: 5, B: 5, C: 5, D: 5 },
    hoursIX: {},
    additionalTask: "Guru Wali",
    additionalHours: 2,
    totalHours: 22
  },
  {
    id: 1201, // Second entry for same teacher
    no: "",
    name: "Mukhamad Yunus, S.Pd",
    nip: "-",
    rank: "-",
    gol: "",
    subject: "Informatika",
    code: "INF-MY",
    hoursVII: {},
    hoursVIII: { A: 3, B: 3 },
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 6
  },
  {
    id: 13,
    no: "13",
    name: "Fahmi Wahyuni, S.Pd",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Bahasa Indonesia",
    code: "BIN-FW",
    hoursVII: { A: 6, B: 6, C: 6, D: 6 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 24
  },
  {
    id: 14,
    no: "14",
    name: "Fakhita Madury, S.Sn",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Seni (Seni Rupa)",
    code: "SENI-FA",
    hoursVII: { A: 2, B: 2, C: 2 },
    hoursVIII: { A: 2, B: 2, C: 2 },
    hoursIX: { A: 2, B: 2, C: 2 },
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 18
  },
  {
    id: 1401,
    no: "",
    name: "Fakhita Madury, S.Sn",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Informatika",
    code: "INF-FA",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 9
  },
  {
    id: 15,
    no: "15",
    name: "Retno Nawangwulan, S. Pd.",
    nip: "-",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Bahasa Inggris",
    code: "BIG-RN",
    hoursVII: {},
    hoursVIII: { A: 4, B: 4, C: 4 },
    hoursIX: { A: 4, B: 4, C: 4 },
    additionalTask: "Wali Kelas VIII C, Guru Wali",
    additionalHours: 4,
    totalHours: 28
  },
  {
    id: 16,
    no: "16",
    name: "Emilia Kartika Sari, S.Pd",
    nip: "-",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Matematika",
    code: "MAT-EM",
    hoursVII: { A: 5, B: 5, C: 5, D: 5 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "Guru Wali",
    additionalHours: 2,
    totalHours: 22
  },
  {
    id: 1601,
    no: "",
    name: "Emilia Kartika Sari, S.Pd",
    nip: "-",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Informatika",
    code: "INF-EM",
    hoursVII: {},
    hoursVIII: { B: 3, C: 3 },
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 6
  },
  {
    id: 17,
    no: "17",
    name: "Akhmad Hariadi, S.Pd",
    nip: "197201011999031001",
    rank: "Penata Muda Tk I",
    gol: "III b",
    subject: "Bahasa Inggris",
    code: "BIG-AH",
    hoursVII: { A: 4, B: 4, C: 4 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "Kepala Perpustakaan, Guru Wali",
    additionalHours: 14,
    totalHours: 26
  },
  {
    id: 1701,
    no: "",
    name: "Akhmad Hariadi, S.Pd",
    nip: "197201011999031001",
    rank: "Penata Muda Tk I",
    gol: "III b",
    subject: "Bahasa Inggris", // Likely typo in source, meant Informatika or similar based on hours
    code: "INF-AH",
    hoursVIII: {},
    hoursIX: { A: 3, B: 3 },
    hoursVII: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 6
  }
];