import { TeacherData, Student } from './types';

export const CLASSES = ['VII A', 'VII B', 'VII C', 'VIII A', 'VIII B', 'VIII C', 'IX A', 'IX B', 'IX C'];

export interface ScheduleRow {
  jam: string;
  waktu: string;
  activity?: string;
  isBreak?: boolean;
}

export interface DaySchedule {
  day: string;
  rows: ScheduleRow[];
  allocatableSlots: string[];
}

export const COLOR_PALETTE = [
  'bg-red-100 text-red-800 border-red-200',
  'bg-orange-100 text-orange-800 border-orange-200',
  'bg-amber-100 text-amber-800 border-amber-200',
  'bg-yellow-100 text-yellow-800 border-yellow-200',
  'bg-lime-100 text-lime-800 border-lime-200',
  'bg-green-100 text-green-800 border-green-200',
  'bg-emerald-100 text-emerald-800 border-emerald-200',
  'bg-teal-100 text-teal-800 border-teal-200',
  'bg-cyan-100 text-cyan-800 border-cyan-200',
  'bg-sky-100 text-sky-800 border-sky-200',
  'bg-blue-100 text-blue-800 border-blue-200',
  'bg-indigo-100 text-indigo-800 border-indigo-200',
  'bg-violet-100 text-violet-800 border-violet-200',
  'bg-purple-100 text-purple-800 border-purple-200',
  'bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200',
  'bg-pink-100 text-pink-800 border-pink-200',
  'bg-rose-100 text-rose-800 border-rose-200',
  'bg-stone-100 text-stone-800 border-stone-200',
  'bg-blue-50 text-blue-900 border-blue-200',
  'bg-red-50 text-red-900 border-red-200',
];

export const SCHEDULE_DATA: DaySchedule[] = [
  {
    day: "SENIN",
    allocatableSlots: ["2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 06.45", activity: "Persiapan Upacara Bendera", isBreak: true },
      { jam: "1", waktu: "06.45 - 07.40", activity: "Upacara Bendera", isBreak: true },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "SELASA",
    allocatableSlots: ["1", "2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Ar-Rahman", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "RABU",
    allocatableSlots: ["1", "2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Al Waqi'ah", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "KAMIS",
    allocatableSlots: ["1", "2", "3", "4", "5", "6", "7", "8"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Isitighotsah", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah", isBreak: true },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "JUM'AT",
    allocatableSlots: ["1", "2", "3", "4", "5"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Yasin", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
    ]
  },
  {
    day: "SABTU",
    allocatableSlots: ["2", "3", "4", "5", "6"],
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Asma'ul Husna dan Juz 'Amma", isBreak: true },
      { jam: "1", waktu: "07.00 - 07.40", activity: "Sabtu Sehat Jiwa Raga", isBreak: true },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat", isBreak: true },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 12.00", activity: "Sholat Dhuhur Berjamaah", isBreak: true },
      { jam: "", waktu: "", activity: "Kegiatan Pengembangan Diri (Ekstra Kurikuler)", isBreak: true },
    ]
  }
];

export const TEACHER_DATA: TeacherData[] = [
  {
    id: 1,
    no: "1",
    name: "Dra. Sri Hayati",
    nip: "196702041992022006",
    rank: "Penata Tk. I",
    gol: "III d",
    subject: "Bahasa Indonesia",
    code: "BIN-SH",
    hoursVII: {},
    hoursVIII: { B: 6, C: 6 },
    hoursIX: { A: 6, B: 6, C: 6 },
    additionalTask: "Wali Kelas IX B, Guru Wali",
    additionalHours: 4,
    totalHours: 34
  },
  {
    id: 2,
    no: "2",
    name: "Bakhtiar Rifai, SE",
    nip: "196610011993031009",
    rank: "Penata Tk. I",
    gol: "III d",
    subject: "Ilmu Pengetahuan Sosial",
    code: "IPS-BR",
    hoursVII: {},
    hoursVIII: { A: 4, B: 4, C: 4 },
    hoursIX: {},
    additionalTask: "Kepala Laboratorium, Guru Wali",
    additionalHours: 14,
    totalHours: 26
  },
  {
    id: 3,
    no: "3",
    name: "Moch. Husain Rifai Hamzah, S.Pd.",
    nip: "197504112008011011",
    rank: "Penata Muda Tk I",
    gol: "III b",
    subject: "Penjas Orkes",
    code: "PJOK-MH",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: { A: 3, B: 3, C: 3 },
    hoursIX: { A: 3, B: 3, C: 3 },
    additionalTask: "Guru Wali, Wali Kelas IX A",
    additionalHours: 4,
    totalHours: 31
  },
  {
    id: 4,
    no: "4",
    name: "Rudi Hermawan, S.Pd.I",
    nip: "197305152008011003",
    rank: "Penata Muda",
    gol: "III a",
    subject: "Pendidikan Agama Islam",
    code: "PAI-RH",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: { A: 3, B: 3, C: 3 },
    hoursIX: { A: 3, B: 3, C: 3 },
    additionalTask: "Guru Wali",
    additionalHours: 2,
    totalHours: 29
  },
  {
    id: 5,
    no: "5",
    name: "Okha Devi Anggraini, S.Pd.",
    nip: "199610232024212008",
    rank: "Penata Muda",
    gol: "III a",
    subject: "Bimbingan Konseling",
    code: "BK-OD",
    hoursVII: { A: 1, B: 1, C: 1 },
    hoursVIII: {},
    hoursIX: { A: 1, B: 1, C: 1 },
    additionalTask: "Wali Kelas VII C, Guru Wali",
    additionalHours: 4,
    totalHours: 10
  },
  {
    id: 6,
    no: "6",
    name: "Eka Hariyati, S. Pd.",
    nip: "199212172024212003",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "PPKn",
    code: "PKN-EH",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: { A: 3, B: 3, C: 3 },
    hoursIX: { A: 3, B: 3, C: 3 },
    additionalTask: "Wali Kelas VIII B, Guru Wali",
    additionalHours: 4,
    totalHours: 31
  },
  {
    id: 7,
    no: "7",
    name: "Mikoe Wahyudi Putra, ST., S. Pd.",
    nip: "198506012024211004",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Bimbingan Konseling",
    code: "BK-MW",
    hoursVII: {},
    hoursVIII: { A: 1, B: 1, C: 1 },
    hoursIX: {},
    additionalTask: "Wakasek, Guru Wali",
    additionalHours: 14,
    totalHours: 17
  },
  {
    id: 8,
    no: "8",
    name: "Purnadi, S. Pd.",
    nip: "199606192024211001",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Matematika",
    code: "MAT-PU",
    hoursVII: {},
    hoursVIII: { B: 5, C: 5 },
    hoursIX: { A: 5, B: 5, C: 5 },
    additionalTask: "Wali Kelas IX C, Guru Wali",
    additionalHours: 4,
    totalHours: 29
  },
  {
    id: 9,
    no: "9",
    name: "Israfin Maria Ulfa, S.Pd",
    nip: "199612212024212004",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Ilmu Pengetahuan Sosial",
    code: "IPS-MU",
    hoursVII: { A: 4, B: 4, C: 4 },
    hoursVIII: {},
    hoursIX: { A: 4, B: 4, C: 4 },
    additionalTask: "Wali Kelas VII A, Guru Wali",
    additionalHours: 4,
    totalHours: 28
  },
  {
    id: 10,
    no: "10",
    name: "Syadam Budi Satrianto, S.Pd",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Bahasa Jawa",
    code: "BAJA-SB",
    hoursVII: { A: 2, B: 2, C: 2 },
    hoursVIII: { A: 2, B: 2, C: 2 },
    hoursIX: { A: 2, B: 2, C: 2 },
    additionalTask: "Wali Kelas VIII A, Guru Wali",
    additionalHours: 4,
    totalHours: 22
  },
  {
    id: 11,
    no: "11",
    name: "Rebby Dwi Prataopu, S.Si",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Ilmu Pengetahuan Alam",
    code: "IPA-RB",
    hoursVII: { A: 5, B: 5 }, // Inferred from "5 5"
    hoursVIII: {},
    hoursIX: { A: 5, B: 5, C: 5 },
    additionalTask: "Wali Kelas VII B, Guru Wali",
    additionalHours: 4,
    totalHours: 29
  },
  {
    id: 12,
    no: "12",
    name: "Mukhamad Yunus, S.Pd",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Ilmu Pengetahuan Alam",
    code: "IPA-MY",
    hoursVII: {},
    hoursVIII: { A: 5, B: 5, C: 5, D: 5 },
    hoursIX: {},
    additionalTask: "Guru Wali",
    additionalHours: 2,
    totalHours: 22
  },
  {
    id: 1201, // Second entry for same teacher
    no: "",
    name: "Mukhamad Yunus, S.Pd",
    nip: "-",
    rank: "-",
    gol: "",
    subject: "Informatika",
    code: "INF-MY",
    hoursVII: {},
    hoursVIII: { A: 3, B: 3 },
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 6
  },
  {
    id: 13,
    no: "13",
    name: "Fahmi Wahyuni, S.Pd",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Bahasa Indonesia",
    code: "BIN-FW",
    hoursVII: { A: 6, B: 6, C: 6, D: 6 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 24
  },
  {
    id: 14,
    no: "14",
    name: "Fakhita Madury, S.Sn",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Seni (Seni Rupa)",
    code: "SENI-FA",
    hoursVII: { A: 2, B: 2, C: 2 },
    hoursVIII: { A: 2, B: 2, C: 2 },
    hoursIX: { A: 2, B: 2, C: 2 },
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 18
  },
  {
    id: 1401,
    no: "",
    name: "Fakhita Madury, S.Sn",
    nip: "-",
    rank: "GTT",
    gol: "",
    subject: "Informatika",
    code: "INF-FA",
    hoursVII: { A: 3, B: 3, C: 3 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 9
  },
  {
    id: 15,
    no: "15",
    name: "Retno Nawangwulan, S. Pd.",
    nip: "-",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Bahasa Inggris",
    code: "BIG-RN",
    hoursVII: {},
    hoursVIII: { A: 4, B: 4, C: 4 },
    hoursIX: { A: 4, B: 4, C: 4 },
    additionalTask: "Wali Kelas VIII C, Guru Wali",
    additionalHours: 4,
    totalHours: 28
  },
  {
    id: 16,
    no: "16",
    name: "Emilia Kartika Sari, S.Pd",
    nip: "-",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Matematika",
    code: "MAT-EM",
    hoursVII: { A: 5, B: 5, C: 5, D: 5 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "Guru Wali",
    additionalHours: 2,
    totalHours: 22
  },
  {
    id: 1601,
    no: "",
    name: "Emilia Kartika Sari, S.Pd",
    nip: "-",
    rank: "Ahli Pertama",
    gol: "IX",
    subject: "Informatika",
    code: "INF-EM",
    hoursVII: {},
    hoursVIII: { B: 3, C: 3 },
    hoursIX: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 6
  },
  {
    id: 17,
    no: "17",
    name: "Akhmad Hariadi, S.Pd",
    nip: "197201011999031001",
    rank: "Penata Muda Tk I",
    gol: "III b",
    subject: "Bahasa Inggris",
    code: "BIG-AH",
    hoursVII: { A: 4, B: 4, C: 4 },
    hoursVIII: {},
    hoursIX: {},
    additionalTask: "Kepala Perpustakaan, Guru Wali",
    additionalHours: 14,
    totalHours: 26
  },
  {
    id: 1701,
    no: "",
    name: "Akhmad Hariadi, S.Pd",
    nip: "197201011999031001",
    rank: "Penata Muda Tk I",
    gol: "III b",
    subject: "Bahasa Inggris", // Likely typo in source, meant Informatika or similar based on hours
    code: "INF-AH",
    hoursVIII: {},
    hoursIX: { A: 3, B: 3 },
    hoursVII: {},
    additionalTask: "-",
    additionalHours: 0,
    totalHours: 6
  }
];

export const INITIAL_STUDENTS: Student[] = [
  { id: "1", className: "VII A", name: "ACSELIN UKE DWINANTA" },
  { id: "2", className: "VII A", name: "AHMAD DWI NAVI SAPUTRA" },
  { id: "3", className: "VII A", name: "AKIRA MUMTAZA GHULAM MAHRON" },
  { id: "4", className: "VII A", name: "ANGGITAH MAHARANI" },
  { id: "5", className: "VII A", name: "ARIMBI AUNI MAYANGSARI" },
  { id: "6", className: "VII A", name: "ARSY TIRTASYA PRAYOGI ISBIANTO" },
  { id: "7", className: "VII A", name: "DEFIANA NUR RAHMA" },
  { id: "8", className: "VII A", name: "DINDA RESTYNING RAHAYU" },
  { id: "9", className: "VII A", name: "IRKHAM ARTHUR MAULANA" },
  { id: "10", className: "VII A", name: "KADITA NATHANIA" },
  { id: "11", className: "VII A", name: "MOHAMMAD ROFIQ ARDIANSYAH" },
  { id: "12", className: "VII A", name: "MUHAMMAD AZZAM NUR ALIF" },
  { id: "13", className: "VII A", name: "MUHAMMAD ARDITIYO SEBASTIAN" },
  { id: "14", className: "VII A", name: "MUHAMMAD EZZAR ALI YUDHA" },
  { id: "15", className: "VII A", name: "MUHAMMAD FAIZ QISBIY ROMADHONI" },
  { id: "16", className: "VII A", name: "OLIVIA ADELLA NAZAHRA" },
  { id: "17", className: "VII A", name: "QOTRUNNADA SALSABILA AKMAL" },
  { id: "18", className: "VII A", name: "RAMA SULTHAN AULIYA AHMAD" },
  { id: "19", className: "VII A", name: "REFAN AZZAM ANUGRAH" },
  { id: "20", className: "VII A", name: "SEPTIA INDAH WULANDARI" },
  { id: "21", className: "VII A", name: "SOEGIARTO WIJAYA" },
  { id: "22", className: "VII A", name: "STEFANI ANANDA RAHMADHANI" },
  { id: "23", className: "VII A", name: "VIRDY PUTRI HARUM KUSUMA" },
  { id: "24", className: "VII A", name: "ZAINI ALI MAHMUD" },
  { id: "25", className: "VII A", name: "ZAVERIO AMSYAR RAFFASYA" },
  { id: "26", className: "VII B", name: "ACHMAD FATAH ADI DARMA" },
  { id: "27", className: "VII B", name: "ARGA ARDIANSA" },
  { id: "28", className: "VII B", name: "AVYKA VERA JUNYARTHA" },
  { id: "29", className: "VII B", name: "DENIS ANGGORO" },
  { id: "30", className: "VII B", name: "DIRLY MICHELE FEBRYAN SUSANTO" },
  { id: "31", className: "VII B", name: "DWI ANDIKA PUTRA SETIAWAN" },
  { id: "32", className: "VII B", name: "FEMILYA QONITA ARINIL HAQ" },
  { id: "33", className: "VII B", name: "HIKMATUL MEISYAH ANJANI" },
  { id: "34", className: "VII B", name: "IQBAL MAULANA AL AZZAM" },
  { id: "35", className: "VII B", name: "KASIH PUTRI SURYA NINGRUM" },
  { id: "36", className: "VII B", name: "KIKI FATMAWATI" },
  { id: "37", className: "VII B", name: "KRIDHO HERVA NATASYA PUTRI" },
  { id: "38", className: "VII B", name: "MOKHAMAD FARA BARIQ SAPUTRA" },
  { id: "39", className: "VII B", name: "MUCHAMMAD ILYAS NUR ADINATA" },
  { id: "40", className: "VII B", name: "MUHAMMAD FARHAN MAULANA" },
  { id: "41", className: "VII B", name: "MUHAMMAD KHOIRUL ANAM" },
  { id: "42", className: "VII B", name: "MUHAMMAD SONIUL ULUMI" },
  { id: "43", className: "VII B", name: "NIZHAR ADITYA ROHMAN" },
  { id: "44", className: "VII B", name: "NUR AINI AGUSTIN" },
  { id: "45", className: "VII B", name: "REVALINA DWI RATNASARI" },
  { id: "46", className: "VII B", name: "SAKA BUANA IKSAN WIJAYANTO" },
  { id: "47", className: "VII B", name: "SYAHRIL FIKRI AMRULLOH" },
  { id: "48", className: "VII B", name: "WAHYU ALIFIANSYAH PUTRA MANGKU B." },
  { id: "49", className: "VII B", name: "WENIDA EKA ANADIA PUTRI" },
  { id: "50", className: "VII B", name: "DZAKIYYA TALITA ZAHRA" },
  { id: "51", className: "VII B", name: "RANIA SYAFA'A PUTRI IMANSYAH" },
  { id: "52", className: "VII B", name: "MOH. DAFFA FAUZAN WIFQULKHOIR" },
  { id: "53", className: "VII C", name: "AISYAH AYU LESTARI" },
  { id: "54", className: "VII C", name: "AISYAH ZANETA SALSABILLA" },
  { id: "55", className: "VII C", name: "ALFARO FEBRIANSYAH WAHYUDI" },
  { id: "56", className: "VII C", name: "APRILIA DWI LESTARI" },
  { id: "57", className: "VII C", name: "CHILYATUZ ZAKIA AINA SALSABILA" },
  { id: "58", className: "VII C", name: "DHAFA SATRIAWAN PRATAMA" },
  { id: "59", className: "VII C", name: "DINDA AKILA PRATIWI" },
  { id: "60", className: "VII C", name: "ELINA ASTRIT YUNEDY" },
  { id: "61", className: "VII C", name: "ENJELINA MIKE ANGGUN LESTARI" },
  { id: "62", className: "VII C", name: "FANI RAHMA ADTYA" },
  { id: "63", className: "VII C", name: "FATALARIK KHAIRUSANI IBNU YAKSHA" },
  { id: "64", className: "VII C", name: "HAIKAL RAYSHA FACHRUDDIN" },
  { id: "65", className: "VII C", name: "HARDIAN SYAHPUTRA" },
  { id: "66", className: "VII C", name: "KIRANA DINAR FADHILLAH QAIS" },
  { id: "67", className: "VII C", name: "JUSTIN GILBERT APRILIO HALIM" },
  { id: "68", className: "VII C", name: "MAULINDA KUSUMA" },
  { id: "69", className: "VII C", name: "MOHAMAD IZAM HAIKAL NAFIS" },
  { id: "70", className: "VII C", name: "MOHAMMAD DAFFA MAULANA AWWALUDDIN" },
  { id: "71", className: "VII C", name: "MUHAMAD DIMAS SAPUTRA" },
  { id: "72", className: "VII C", name: "DWI AZZAHRA RAMADHANI" },
  { id: "73", className: "VII C", name: "MUHAMMAD EZAR NAFIL" },
  { id: "74", className: "VII C", name: "MUHAMMAD FARIS ALFARIZI" },
  { id: "75", className: "VII C", name: "MUHAMMAD NICOLA VERDIANSYAH" },
  { id: "76", className: "VII C", name: "YUWIETA TRI ANGGREINY" },
  { id: "77", className: "VII C", name: "ZAFAR SIDIQ" },
  { id: "78", className: "VIII A", name: "ACHMAD KIESHA RIZQI ANDIKA" },
  { id: "79", className: "VIII A", name: "ALANSKY VANI ARIEFKY PUTRA" },
  { id: "80", className: "VIII A", name: "ALMIRAH YUNITA" },
  { id: "81", className: "VIII A", name: "ANA NAYLA SALSABILLA" },
  { id: "82", className: "VIII A", name: "ARIYA FERDIANSA" },
  { id: "83", className: "VIII A", name: "ASIFA AMELIA PUTRI" },
  { id: "84", className: "VIII A", name: "ASMIAR AFIQOH RACHMADHANI" },
  { id: "85", className: "VIII A", name: "AURA MIFVATUL PUTRI" },
  { id: "86", className: "VIII A", name: "AVELIYAN AGHIL EDDYANZA" },
  { id: "87", className: "VIII A", name: "IMELDA NAJWA AYU KUMALASARI" },
  { id: "88", className: "VIII A", name: "INDRA BAGUS SAPUTRA" },
  { id: "89", className: "VIII A", name: "JESICA APRILIA AYUNENGTIAS" },
  { id: "90", className: "VIII A", name: "MOCH DEVAN SAPUTRA" },
  { id: "91", className: "VIII A", name: "MOHAMMAD DAFFA" },
  { id: "92", className: "VIII A", name: "MUH. REVAN RIZKI PRATAMA" },
  { id: "93", className: "VIII A", name: "MUHAMMAD BAYU SAPUTRO" },
  { id: "94", className: "VIII A", name: "MUHAMMAD NASRUL MUJAQQI" },
  { id: "95", className: "VIII A", name: "MUKHAMAD ILYAS RIZKY ABDILLAH" },
  { id: "96", className: "VIII A", name: "NADZAR PANDU PRAHASTA" },
  { id: "97", className: "VIII A", name: "NAURA CECILYA ANGELYCA" },
  { id: "98", className: "VIII A", name: "NAURAH SALSABILA" },
  { id: "99", className: "VIII A", name: "NAZWA NATASYA PUTRI" },
  { id: "100", className: "VIII A", name: "PUPUT KUMALA SARI" },
  { id: "101", className: "VIII A", name: "PUTRI EKA NILASARI" },
  { id: "102", className: "VIII A", name: "PUTRI JUWITA SARI" },
  { id: "103", className: "VIII A", name: "RAFIQ MAULANA" },
  { id: "104", className: "VIII A", name: "REVAND DWI AL DIANO" },
  { id: "105", className: "VIII A", name: "RIYADHUL BUKHORI" },
  { id: "106", className: "VIII A", name: "KYANO RICKY SAPUTRA" },
  { id: "107", className: "VIII A", name: "SERLIYAH CAHYA FITRIANI" },
  { id: "108", className: "VIII A", name: "SESILLIA ANGELINA PUTRI" },
  { id: "109", className: "VIII A", name: "SHEGA RAMADHANI" },
  { id: "110", className: "VIII A", name: "VALENCIA SELLA FENDY SAFIRA" },
  { id: "111", className: "VIII A", name: "WAHYU NUR AHMAD SETIO BUDI" },
  { id: "112", className: "VIII A", name: "YUSRIEL ADI ALFAREZA" },
  { id: "113", className: "VIII B", name: "ACHMAD DAFFA KURNIAWAN" },
  { id: "114", className: "VIII B", name: "AHMAD RAVA MAULANA" },
  { id: "115", className: "VIII B", name: "AHMAD YONGKY ROFIKUL A'LA" },
  { id: "116", className: "VIII B", name: "AKHMAD RIFKI SAMSUL ANGGORO" },
  { id: "117", className: "VIII B", name: "ALDELIA PUTRI ANNUROH" },
  { id: "118", className: "VIII B", name: "ALIVIA AZZAHRA" },
  { id: "119", className: "VIII B", name: "AMELIA DWI AMANDA SARI" },
  { id: "120", className: "VIII B", name: "BISMA PUTRA RAMADHAN" },
  { id: "121", className: "VIII B", name: "CINTIA ZIFA PERMATA KIRANA" },
  { id: "122", className: "VIII B", name: "DESYIFA ADELIA EKA FIRNANDA" },
  { id: "123", className: "VIII B", name: "DEWI AVIKA PUTRI" },
  { id: "124", className: "VIII B", name: "DWI KANAYA PUTRI" },
  { id: "125", className: "VIII B", name: "FADILLAH AINI KHOMARI" },
  { id: "126", className: "VIII B", name: "IVANDER ZAKI ANGGARA" },
  { id: "127", className: "VIII B", name: "JULIANA PUTRI" },
  { id: "128", className: "VIII B", name: "KELFIN ANDIKA PRATAMA" },
  { id: "129", className: "VIII B", name: "KYANOE LUCKY WIJJAYA" },
  { id: "130", className: "VIII B", name: "LOEIS ADITYA PUTRA" },
  { id: "131", className: "VIII B", name: "MOCHAMAD VICKY WAHYUPI" },
  { id: "132", className: "VIII B", name: "MUHAMAD AYUBI ANAS" },
  { id: "133", className: "VIII B", name: "MUHAMMAD ILHAM SYAFI'I" },
  { id: "134", className: "VIII B", name: "MUHAMMAD RENDI ADITYA" },
  { id: "135", className: "VIII B", name: "MUHAMMAD REZZA SETYAWAN" },
  { id: "136", className: "VIII B", name: "MUHAMMAD YAFIUL HAMZI" },
  { id: "137", className: "VIII B", name: "MUKHAMMAD ARYA MAULANA" },
  { id: "138", className: "VIII B", name: "NARITA SILVIA DEWI" },
  { id: "139", className: "VIII B", name: "NAYLA HIDAYATUN NUFUS" },
  { id: "140", className: "VIII B", name: "OKTAVIAN ERGIANSYAH" },
  { id: "141", className: "VIII B", name: "RIZKI VERANIKA ANDINA SOLIKHAH" },
  { id: "142", className: "VIII B", name: "ROSYIDAH WULANDARI" },
  { id: "143", className: "VIII B", name: "TUNGGUL DIAS ARIANSYAH" },
  { id: "144", className: "VIII B", name: "WILDA PRATIWI" },
  { id: "145", className: "VIII B", name: "WILDHA CHELSEA META OCTAVIA" },
  { id: "146", className: "VIII B", name: "ASTI DWI NATHANIA PUTRI" },
  { id: "147", className: "VIII C", name: "AHMAD ZAIYANI WARDANI" },
  { id: "148", className: "VIII C", name: "ARIEL SENNA DWI FIRMANSYAH" },
  { id: "149", className: "VIII C", name: "AVRILIA EKA RAHMAWATI" },
  { id: "150", className: "VIII C", name: "AYU ANDIRA" },
  { id: "151", className: "VIII C", name: "AZAM IBI SYEVIK" },
  { id: "152", className: "VIII C", name: "AZKA ATALARIC ZACHARI KHALFANI" },
  { id: "153", className: "VIII C", name: "CINTA RAHMA ASIYA" },
  { id: "154", className: "VIII C", name: "DAUD ATHOURROHMAN KAMAL" },
  { id: "155", className: "VIII C", name: "DINI OLIVIA PUTRI" },
  { id: "156", className: "VIII C", name: "DIO ARSYAH MAULANA" },
  { id: "157", className: "VIII C", name: "FERLIN ELSA HAVIVA" },
  { id: "158", className: "VIII C", name: "JANITA KAMILA ZAMAN" },
  { id: "159", className: "VIII C", name: "JESLYN SHAILA LEXIA AMORA" },
  { id: "160", className: "VIII C", name: "KYANNO RENDRA BUDI PRATAMA" },
  { id: "161", className: "VIII C", name: "LUTVI RASYA RAMADHAN" },
  { id: "162", className: "VIII C", name: "MAHFIDHO ZAKIYATUS SHAFA" },
  { id: "163", className: "VIII C", name: "MARCELLINO MAULANA MAZBULLAH" },
  { id: "164", className: "VIII C", name: "MARTHA DWI TARADILA" },
  { id: "165", className: "VIII C", name: "MIFTAKHUL JANAH" },
  { id: "166", className: "VIII C", name: "MOHAMMAD DAVID ALFIANSYAH" },
  { id: "167", className: "VIII C", name: "MUHAMMAD FAIS ILHAM" },
  { id: "168", className: "VIII C", name: "MUHAMMAD IQBAL ALIE MUZAKI" },
  { id: "169", className: "VIII C", name: "MUHAMMAD KHADID ANWARY" },
  { id: "170", className: "VIII C", name: "MUHAMMAD NASYA PRADIPTA OKTAFA" },
  { id: "171", className: "VIII C", name: "MUHAMMAD WAHYU RAMDHANI" },
  { id: "172", className: "VIII C", name: "MUKHAMAT FAHRUL" },
  { id: "173", className: "VIII C", name: "MUKHAMMAD RIZKY WANDIAN SYAH" },
  { id: "174", className: "VIII C", name: "NADYA LOVITA PUTRI" },
  { id: "175", className: "VIII C", name: "NAFISHATUL MUFIDAH" },
  { id: "176", className: "VIII C", name: "NERLITA ADELIA PUTRI" },
  { id: "177", className: "VIII C", name: "NOVALUNA ADINDA PUTRI" },
  { id: "178", className: "VIII C", name: "RENO AIDHIL ELMAWANTO" },
  { id: "179", className: "VIII C", name: "RIYO FAFA ALAMSYAH" },
  { id: "180", className: "VIII C", name: "SILVI ADELLYA ANDINI" },
  { id: "181", className: "VIII C", name: "TEGAR HENDY RISWANTO" },
  { id: "182", className: "IX A", name: "ABEL AULIA PASA RAMADANI" },
  { id: "183", className: "IX A", name: "ADITYA FIRMANSYAH" },
  { id: "184", className: "IX A", name: "AHMAD NIAM IZZI AFKAR" },
  { id: "185", className: "IX A", name: "DAFA RISKI EKA SYAHPUTRA" },
  { id: "186", className: "IX A", name: "DEA NAYLATUL AFITA" },
  { id: "187", className: "IX A", name: "DHEA ZASKIA OLIVIA PUTRI" },
  { id: "188", className: "IX A", name: "ENGGELITA REGINA PUTRI" },
  { id: "189", className: "IX A", name: "FAREL ANDRIANSAH" },
  { id: "190", className: "IX A", name: "FURI ANGELIKA PUTRI" },
  { id: "191", className: "IX A", name: "JESICHA PUTRI RAMADHANI" },
  { id: "192", className: "IX A", name: "JIHAN DEA VALQOHI" },
  { id: "193", className: "IX A", name: "M. FERDY SANTOSO" },
  { id: "194", className: "IX A", name: "MICHELIA ANDARA PUTRI AGUSTINA" },
  { id: "195", className: "IX A", name: "MUHAMAD ADITIYA SUGIHARTO" },
  { id: "196", className: "IX A", name: "MUHAMAD RIFKI AFANDI" },
  { id: "197", className: "IX A", name: "MUHAMMAD AL AMIN" },
  { id: "198", className: "IX A", name: "MUHAMMAD BAHRUDIN NICOLAS SAPUTRA" },
  { id: "199", className: "IX A", name: "MUHAMMAD HAIKAL DWI APRIANSYAH" },
  { id: "200", className: "IX A", name: "MUHAMMAD REHAN MEYLANO" },
  { id: "201", className: "IX A", name: "MUHAMMAD RIZQI FATKUR ROZI" },
  { id: "202", className: "IX A", name: "NABILA SRI WULANDARI" },
  { id: "203", className: "IX A", name: "RIFKI ARDIAN SYAPUTRA" },
  { id: "204", className: "IX A", name: "SALSABILLA PUTRI RAMADHANI" },
  { id: "205", className: "IX A", name: "SASKIA AISYAH AZZAHRA" },
  { id: "206", className: "IX A", name: "SHERLIN HERLA AZZAHRA" },
  { id: "207", className: "IX A", name: "SLAMET RIZKI GALI RIMBA ANGKASA" },
  { id: "208", className: "IX A", name: "VALENSYA DWI PUTRI WIJAYA" },
  { id: "209", className: "IX A", name: "WILDAN DIMAS DWI ANANDA" },
  { id: "210", className: "IX A", name: "DEFANO HAIKAL RAMADHAN" },
  { id: "211", className: "IX A", name: "SAMSUL NURUL HUDA" },
  { id: "212", className: "IX B", name: "ABHEL ECHA TRIOCTAVIA NATASYA" },
  { id: "213", className: "IX B", name: "ADITYA SAPUTRA" },
  { id: "214", className: "IX B", name: "AKBAR KHAFI AS SHAFFAAT" },
  { id: "215", className: "IX B", name: "Alviansyah Radityah Putra" },
  { id: "216", className: "IX B", name: "ANINDITA WIDIYA CAHYANI" },
  { id: "217", className: "IX B", name: "Bayu Widiat Moko" },
  { id: "218", className: "IX B", name: "CANTICA ENGEL AULIA SHAVIRA" },
  { id: "219", className: "IX B", name: "FANIA KHOIROTUL UMMAH" },
  { id: "220", className: "IX B", name: "HANUM PUSPITA SARI" },
  { id: "221", className: "IX B", name: "KEYVIN RAJA DIRHAM" },
  { id: "222", className: "IX B", name: "Kinansye Novita Kreyti" },
  { id: "223", className: "IX B", name: "M. REVA INDRA RAMADHANI" },
  { id: "224", className: "IX B", name: "MOHAMMAD SURYA PUTRA JUANDA" },
  { id: "225", className: "IX B", name: "MUHAMMAD AZZAM AUFA RIZKY" },
  { id: "226", className: "IX B", name: "MUHAMMAD EDO PRATAMA" },
  { id: "227", className: "IX B", name: "MUHAMMAD RIZKI FEBRIAN PRATAMA" },
  { id: "228", className: "IX B", name: "NIHAYATUL HIMMAH" },
  { id: "229", className: "IX B", name: "Ninis Daniyah Permatasari" },
  { id: "230", className: "IX B", name: "PUTUT EKA DWI PRADANA" },
  { id: "231", className: "IX B", name: "RENO ARDIKA FEBRIANSYAH" },
  { id: "232", className: "IX B", name: "REZKY REVAN'A ADITYA" },
  { id: "233", className: "IX B", name: "ROHMATUN NADIYAH" },
  { id: "234", className: "IX B", name: "Siwetul Jennah" },
  { id: "235", className: "IX B", name: "TONI ADI SETIAWAN" },
  { id: "236", className: "IX B", name: "VEHANA RECHA INEZHA" },
  { id: "237", className: "IX B", name: "VISCHA AZZAHRA PUTRI" },
  { id: "238", className: "IX B", name: "WINDA SRI ASTUTIK" },
  { id: "239", className: "IX B", name: "YUSRIL ALFAREL NUGRAHA" },
  { id: "240", className: "IX B", name: "ZIDAN RAHMAT ADITYA" },
  { id: "241", className: "IX B", name: "YUSUF ADITYA ALIN PRATAMA" },
  { id: "242", className: "IX C", name: "ADINDA DWI PRASETYAWAN" },
  { id: "243", className: "IX C", name: "AHKMAD IRCHAM ALI AZKIYA JAZULY" },
  { id: "244", className: "IX C", name: "AKHMAD EGA JULIANO" },
  { id: "245", className: "IX C", name: "AMIRULLOH AKBAR" },
  { id: "246", className: "IX C", name: "ANDIEN DINAR FADHILLAH QAIS" },
  { id: "247", className: "IX C", name: "AULIA PUTRY RAUDIATUL JANNAH" },
  { id: "248", className: "IX C", name: "AURELIA FATIMAH YUNITA" },
  { id: "249", className: "IX C", name: "AYU DEVINA EKA PRATIWI" },
  { id: "250", className: "IX C", name: "BINTANG PRATAMA" },
  { id: "251", className: "IX C", name: "CITRA TRIAN ANDINI" },
  { id: "252", className: "IX C", name: "DENIS EKA FEBRIAN" },
  { id: "253", className: "IX C", name: "ELISA DINDA SAVIERA" },
  { id: "254", className: "IX C", name: "FAJAR ADITYA PUTRA" },
  { id: "255", className: "IX C", name: "GRISELDA SANDRA ADELIA" },
  { id: "256", className: "IX C", name: "JASTINE DIAN DWI ALEXTIAN" },
  { id: "257", className: "IX C", name: "KAFRIDA INDAH DWI PRAMESTI" },
  { id: "258", className: "IX C", name: "KRISNA WAHYU ARIYANSYAH" },
  { id: "259", className: "IX C", name: "MIFTAKHUL DWIYANTI" },
  { id: "260", className: "IX C", name: "MOHKAMAT SLAMET PRASETIO" },
  { id: "261", className: "IX C", name: "MUHAMAD THORIQ SHOLIKHUL ULAH" },
  { id: "262", className: "IX C", name: "MUHAMMAD BAGUS DWI SETIAWAN" },
  { id: "263", className: "IX C", name: "MUHAMMAD SYAHLAN AL FARISI" },
  { id: "264", className: "IX C", name: "MUHAMMAD SYAIFUDDIN ZUHRI" },
  { id: "265", className: "IX C", name: "MUKHAMMAD NAFIS  ZANWAR" },
  { id: "266", className: "IX C", name: "PUTRA FAIZ ABILANSA" },
  { id: "267", className: "IX C", name: "RAKA ZA ARKAN AL YAHYA" },
  { id: "268", className: "IX C", name: "RIZKY DWI PRASETYA" },
  { id: "269", className: "IX C", name: "SAHAZIKA GISTIANO MAISEGALUNG" },
  { id: "270", className: "IX C", name: "ACHMAD SAIFUL ANWAR" }
];